### ISSUE TITLE
サポート依頼してください。と表示されて使用ができない

### ISSUE THREAD

**Issue by nana202205** [horoscope-dev/Dalamud.Divination.AetheryteLinkInChat#2]
プラグインインストール後に
「divination.aetherytelinkinchat Error
The plugin divination.aetherytelinkinchat ran into an error.
Contact the plugin developer for support.
Please try restarting your game.」
と表示されて、ゲームを再起動しても同様で使用することができません。
パッチ6.1以前は使用することができていました

**Comment by a1hena** [comment]
fixed for v0.1.0.48, please update plugin.
